services:
  beremvrot:
    container_name: beremvrot
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - nginx
    volumes:
      - ./prisma:/app/prisma
    command: npm run start
    restart: unless-stopped

networks:
  nginx:
    external: true
    name: nginx

volumes:
  prisma:
